### ISSUE TITLE
outra camera 

### ISSUE THREAD

**Issue by sandman21vs** [cryptopasivo/ESP32_NerdMiner#2]
ola, tenho uma tela de mesmo modelo e aparentemente o mesmo driver, voce poderia me dar uma ajuda para saber como fazer a conexao dela pois a minha tela nao tem um pino nomeado a0 
![image](https://user-images.githubusercontent.com/31391404/230528450-77edb588-a3b1-4c12-aa35-b185218d224c.png)

**Comment by BitMaker-hub** [comment]
RST - IO4
CS - IO15
D/C- IO2
DIN - IO18
SCK - IO23
BL - 3v3
5V - 5V
GND - GND
